(() => {
'use strict';
const STORAGE_KEY='digital_card_v2', OLD_STORAGE_KEY='digital_card_v1', THEME_KEY='digital_card_theme_v2';
const defaults={organization:'Kurum / İşletme Adı',organizationSub:'Kurumsal alt başlık',fullName:'Ad Soyad',title:'Ünvan',unit:'Birim / Açıklama',phone1:'',phone2:'',whatsapp:'',email:'',website:'',address:'',mapsUrl:'',instagram:'',facebook:'',youtube:'',whatsappChannel:'',profileImage:'',logoImage:'',brandPrimary:'#063b66',brandSecondary:'#00a6a6',editLocked:false,savedOnce:false};
let data=loadData(),deferredInstallPrompt=null,lastQrSvg='',draftProfile='',draftLogo='';
const $=id=>document.getElementById(id),form=$('editorForm'),editorDialog=$('editorDialog'),qrDialog=$('qrDialog'),installDialog=$('installDialog');
function loadData(){try{const v2=localStorage.getItem(STORAGE_KEY);if(v2)return {...defaults,...JSON.parse(v2)};const old=localStorage.getItem(OLD_STORAGE_KEY);if(old){const migrated={...defaults,...JSON.parse(old),savedOnce:true,editLocked:true};localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated}}catch(e){console.warn(e)}return {...defaults}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function showToast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
function text(id,v,f){$(id).textContent=(v||'').trim()||f}
function validHex(v,f){return /^#[0-9a-f]{6}$/i.test(v||'')?v:f}
function applyBrand(){data.brandPrimary=validHex(data.brandPrimary,defaults.brandPrimary);data.brandSecondary=validHex(data.brandSecondary,defaults.brandSecondary);document.documentElement.style.setProperty('--brand-primary',data.brandPrimary);document.documentElement.style.setProperty('--brand-secondary',data.brandSecondary);document.querySelector('meta[name="theme-color"]').setAttribute('content',data.brandPrimary)}
function setImage(boxId,imgId,value){const box=$(boxId),img=$(imgId);if(value){img.src=value;box.classList.add('has-img')}else{img.removeAttribute('src');box.classList.remove('has-img')}}
function render(){applyBrand();text('topTitle',data.fullName,'Kartım');text('orgView',data.organization,'Kurum / İşletme Adı');text('orgSubView',data.organizationSub,'Kurumsal alt başlık');text('nameView',data.fullName,'Ad Soyad');text('titleView',data.title,'Ünvan');text('unitView',data.unit,'Birim / Açıklama');text('phoneView',data.phone1||data.phone2,'Telefon eklenmedi');text('emailView',data.email,'E-posta eklenmedi');text('addressView',data.address,'Adres bilgisi eklenmedi.');setImage('profileBox','profileImg',data.profileImage);setImage('logoBox','logoImg',data.logoImage);
$('callBtn').disabled=!(data.phone1||data.phone2);$('waBtn').disabled=!data.whatsapp;$('mailBtn').disabled=!data.email;$('mapBtn').disabled=!(data.mapsUrl||data.address);
document.querySelectorAll('[data-social]').forEach(b=>b.hidden=!data[b.dataset.social]);$('socialSection').hidden=!['website','instagram','facebook','youtube','whatsappChannel'].some(k=>data[k]);
$('editBtn').disabled=!!data.editLocked;$('editBtn').setAttribute('aria-disabled',String(!!data.editLocked));$('editBtn').title=data.editLocked?'Kart kaydedildi. Yeniden düzenlemek için alttaki kilidi açın.':'Kart bilgilerini düzenle';$('unlockEditBtn').hidden=!data.editLocked;const badge=$('lockBadge');badge.textContent=data.editLocked?'Kart kilitli':'Düzenlenebilir';badge.classList.toggle('locked',!!data.editLocked)}
function fillForm(){[...form.elements].forEach(el=>{if(el.name&&Object.hasOwn(data,el.name))el.value=data[el.name]||''});draftProfile=data.profileImage||'';draftLogo=data.logoImage||'';renderDraftPreviews()}
function renderDraftPreviews(){$('profilePreview').src=draftProfile||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2272%22 height=%2272%22%3E%3Crect width=%2272%22 height=%2272%22 fill=%22%23e7edf2%22/%3E%3Ctext x=%2236%22 y=%2243%22 text-anchor=%22middle%22 font-size=%2224%22%3E%F0%9F%91%A4%3C/text%3E%3C/svg%3E';$('logoPreview').src=draftLogo||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2272%22 height=%2272%22%3E%3Crect width=%2272%22 height=%2272%22 fill=%22white%22/%3E%3Ctext x=%2236%22 y=%2243%22 text-anchor=%22middle%22 font-size=%2217%22 fill=%22%23063b66%22 font-family=%22Arial%22%3ELOGO%3C/text%3E%3C/svg%3E'}
function sanitizeUrl(v){v=(v||'').trim();if(!v)return'';return /^[a-z][a-z0-9+.-]*:/i.test(v)?v:'https://'+v}
function phoneHref(v){return'tel:'+String(v||'').replace(/[^+\d]/g,'')}
function whatsappDigits(v){let d=String(v||'').replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.startsWith('0')&&d.length===11)d='90'+d.slice(1);return d}
function openExternal(u){if(u)window.open(u,'_blank','noopener,noreferrer')}
function vEscape(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,')}
function createVCard(){const parts=(data.fullName||'').trim().split(/\s+/),last=parts.length>1?parts.pop():'',first=parts.join(' ');return ['BEGIN:VCARD','VERSION:3.0',`N:${vEscape(last)};${vEscape(first)};;;`,`FN:${vEscape(data.fullName)}`,data.organization?`ORG:${vEscape(data.organization)}`:'',data.title?`TITLE:${vEscape(data.title)}`:'',data.unit?`NOTE:${vEscape(data.unit)}`:'',data.phone1?`TEL;TYPE=CELL,VOICE:${vEscape(data.phone1)}`:'',data.phone2?`TEL;TYPE=WORK,VOICE:${vEscape(data.phone2)}`:'',data.whatsapp?`TEL;TYPE=CELL:${vEscape(data.whatsapp)}`:'',data.email?`EMAIL;TYPE=INTERNET:${vEscape(data.email)}`:'',data.website?`URL:${vEscape(sanitizeUrl(data.website))}`:'',data.address?`ADR;TYPE=WORK:;;${vEscape(data.address)};;;;`:'','END:VCARD'].filter(Boolean).join('\r\n')}
function downloadBlob(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function safeFilename(){return(data.fullName||'dijital-kartvizit').trim().replace(/[^a-z0-9ğüşöçıİĞÜŞÖÇ_-]+/gi,'-').replace(/^-+|-+$/g,'')||'dijital-kartvizit'}
function downloadVCard(){downloadBlob(new Blob(['\ufeff'+createVCard()],{type:'text/vcard;charset=utf-8'}),safeFilename()+'.vcf');showToast('VCF kişi kartı hazırlandı')}
function shareText(){return[data.fullName,data.title,data.organization,data.phone1,data.email,data.website].filter(Boolean).join('\n')}
async function shareCard(){const text=shareText();try{const file=new File([createVCard()],safeFilename()+'.vcf',{type:'text/vcard'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:data.fullName||'Dijital Kartvizit',text,files:[file]})}else if(navigator.share){await navigator.share({title:data.fullName||'Dijital Kartvizit',text})}else if(navigator.clipboard){await navigator.clipboard.writeText(text);showToast('Kart bilgileri panoya kopyalandı')}else downloadVCard()}catch(e){if(e.name!=='AbortError')showToast('Paylaşım başlatılamadı')}}
function renderQr(){const mount=$('qrMount');try{if(!window.LocalQRCode)throw new Error('QR modülü yok');lastQrSvg=window.LocalQRCode.toSvg(createVCard(),{level:'M',margin:4});mount.innerHTML=lastQrSvg}catch(e){console.error(e);lastQrSvg='';mount.innerHTML='<div class="qr-placeholder">QR oluşturulamadı. Kart bilgilerinin çok uzun olmadığını kontrol edin.</div>'}}
async function imageFileToDataUrl(file,{max=640,type='image/jpeg',quality=.86}={}){if(!file)return'';if(!file.type.startsWith('image/'))throw new Error('not image');const raw=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=raw});const scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');if(type==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height)}ctx.drawImage(img,0,0,c.width,c.height);return c.toDataURL(type,quality)}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function showInstallHelp(){const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$('installHelp').innerHTML=ios?'<p><strong>iPhone / iPad:</strong></p><ol><li>Sayfayı Safari ile açın.</li><li><strong>Paylaş</strong> simgesine dokunun.</li><li><strong>Ana Ekrana Ekle</strong> seçeneğini seçin.</li><li><strong>Ekle</strong> ile tamamlayın.</li></ol>':'<p><strong>Android:</strong></p><ol><li>Sayfayı Chrome ile açın.</li><li>Menüden <strong>Uygulamayı yükle</strong> veya <strong>Ana ekrana ekle</strong> seçeneğini kullanın.</li><li>Kurulumu onaylayın.</li></ol>';installDialog.showModal()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;showToast('Uygulama kuruldu')});
$('editBtn').addEventListener('click',()=>{if(data.editLocked)return;fillForm();editorDialog.showModal()});$('closeEditorBtn').addEventListener('click',()=>editorDialog.close());$('cancelEditBtn').addEventListener('click',()=>editorDialog.close());
form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);for(const k of Object.keys(defaults)){if(['profileImage','logoImage','editLocked','savedOnce'].includes(k))continue;data[k]=String(fd.get(k)||'').trim()}data.profileImage=draftProfile;data.logoImage=draftLogo;data.savedOnce=true;data.editLocked=true;try{saveData();render();editorDialog.close();showToast('Kart kaydedildi ve Düzenle kilitlendi')}catch{showToast('Depolama alanı dolu. Görselleri küçültün.')}});
$('profileInput').addEventListener('change',async e=>{try{draftProfile=await imageFileToDataUrl(e.target.files[0],{max:560,type:'image/jpeg',quality:.84});renderDraftPreviews();showToast('Profil fotoğrafı hazır')}catch{showToast('Profil fotoğrafı okunamadı')}});$('logoInput').addEventListener('change',async e=>{try{draftLogo=await imageFileToDataUrl(e.target.files[0],{max:720,type:'image/png'});renderDraftPreviews();showToast('Kurum logosu hazır')}catch{showToast('Logo okunamadı')}});$('removeProfileBtn').addEventListener('click',()=>{draftProfile='';$('profileInput').value='';renderDraftPreviews();showToast('Profil fotoğrafı kaldırıldı')});$('removeLogoBtn').addEventListener('click',()=>{draftLogo='';$('logoInput').value='';renderDraftPreviews();showToast('Logo kaldırıldı')});
$('unlockEditBtn').addEventListener('click',()=>{if(!confirm('Kartı yeniden düzenlemeye açmak istiyor musunuz?'))return;data.editLocked=false;saveData();render();showToast('Düzenleme kilidi açıldı')});
$('callBtn').addEventListener('click',()=>{const p=data.phone1||data.phone2;if(p)location.href=phoneHref(p)});$('waBtn').addEventListener('click',()=>{const d=whatsappDigits(data.whatsapp);if(d)openExternal('https://wa.me/'+d)});$('mailBtn').addEventListener('click',()=>{if(data.email)location.href='mailto:'+encodeURIComponent(data.email)});$('mapBtn').addEventListener('click',()=>{if(data.mapsUrl)openExternal(sanitizeUrl(data.mapsUrl));else if(data.address)openExternal('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(data.address))});$('vcardBtn').addEventListener('click',downloadVCard);$('shareBtn').addEventListener('click',shareCard);
$('qrBtn').addEventListener('click',()=>{qrDialog.showModal();renderQr()});$('closeQrBtn').addEventListener('click',()=>qrDialog.close());$('qrVcardBtn').addEventListener('click',downloadVCard);$('downloadQrBtn').addEventListener('click',()=>{if(!lastQrSvg)return showToast('Önce QR kod oluşturulmalı');downloadBlob(new Blob([lastQrSvg],{type:'image/svg+xml;charset=utf-8'}),safeFilename()+'-QR.svg');showToast('QR kod indirildi')});
$('installBtn').addEventListener('click',async()=>{if(isStandalone())return showToast('Uygulama zaten kurulu');if(deferredInstallPrompt){deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice}catch{}deferredInstallPrompt=null}else showInstallHelp()});$('closeInstallBtn').addEventListener('click',()=>installDialog.close());document.querySelectorAll('[data-social]').forEach(b=>b.addEventListener('click',()=>openExternal(sanitizeUrl(data[b.dataset.social]))));
$('backupBtn').addEventListener('click',()=>{downloadBlob(new Blob([JSON.stringify({version:2,data},null,2)],{type:'application/json'}),safeFilename()+'-yedek.json');showToast('Yedek dosyası oluşturuldu')});$('restoreInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const parsed=JSON.parse(await f.text());data={...defaults,...(parsed.data||parsed),editLocked:true,savedOnce:true};saveData();render();showToast('Yedek geri yüklendi ve kart kilitlendi')}catch{showToast('Geçersiz yedek dosyası')}e.target.value=''});$('resetBtn').addEventListener('click',()=>{if(!confirm('Karttaki tüm kayıtlı bilgileri, görselleri ve kurumsal renkleri sıfırlamak istiyor musunuz?'))return;data={...defaults};saveData();render();showToast('Kart sıfırlandı; Düzenle yeniden aktif')});
function applyTheme(t){document.documentElement.classList.toggle('dark',t==='dark');localStorage.setItem(THEME_KEY,t)}const pref=localStorage.getItem(THEME_KEY)||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');applyTheme(pref);$('themeBtn').addEventListener('click',()=>applyTheme(document.documentElement.classList.contains('dark')?'light':'dark'));
render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(console.error);
})();
